# uncomment to preview locally
#theme: "dendron-jekyll"
remote_theme: dendronhq/dendron-jekyll
title: Unix
logo: "/assets/images/logo.jpg"
exclude: [ "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "*/dendron.template.release.md"
]
footer_content: ""

gh_edit_link: false

# seo
tagline: "A better way to know"
description: "Github Page for jotting down some thoughts. Made using Dendron"
twitter:
  card: summary
  username: dendronhq
author:
  twitter: dendronhq

enable_mathjax: true;
kramdown:
  math_engine: mathjax
defaults:
  -
    scope:
      path: "notes" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/images/logo.png"
